# Generated by Django 4.2.1 on 2023-05-12 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('tasks', '0002_alter_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='contributors',
            field=models.ManyToManyField(null=True, related_name='contributed_task_lists', to='users.profile'),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_task_lists', to='users.profile'),
        ),
    ]
